#pragma once

#include <string>
#include <string_view>

namespace visiform {

inline constexpr int VersionMajor = 1;
inline constexpr int VersionMinor = 0;
inline constexpr int VersionPatch = 21;
inline constexpr std::string_view VersionString = "1.0.21";
inline constexpr std::string_view ProductName = "VisiForm";
inline constexpr std::string_view ProductDescription = "Visage Form Builder";
inline constexpr std::string_view BuildName = "VisiForm 1.0.21";
inline constexpr std::string_view WindowTitle = "VisiForm 1.0.21 - Visage Form Builder";

#ifdef NDEBUG
inline constexpr std::string_view BuildConfiguration = "Release";
#else
inline constexpr std::string_view BuildConfiguration = "Debug";
#endif

inline std::string makeWindowTitle(bool dirty)
{
    std::string title{ WindowTitle };
    if (dirty) {
        title += " *";
    }
    return title;
}

inline std::string aboutDialogText()
{
    return std::string{ ProductName }
        + "\nVersion " + std::string{ VersionString }
        + "\n" + std::string{ ProductDescription }
        + "\nBuild: " + std::string{ BuildConfiguration };
}

inline std::string generatedByComment()
{
    return std::string{ "Generated by " } + std::string{ BuildName };
}

} // namespace visiform
