#include "generator/CMakeEmitter.h"

#include <algorithm>
#include <cctype>
#include <sstream>

namespace visiform::generator {
namespace {

std::string sanitizeProjectNameForCMake(const std::string& value)
{
    std::string sanitized;
    sanitized.reserve(value.size());
    for (char character : value) {
        if (std::isalnum(static_cast<unsigned char>(character)) != 0) {
            sanitized.push_back(character);
        }
        else if (character == '_' || character == '-') {
            sanitized.push_back('_');
        }
    }

    if (sanitized.empty()) {
        return "ExportedVisageProject";
    }
    if (std::isdigit(static_cast<unsigned char>(sanitized.front())) != 0) {
        sanitized.insert(sanitized.begin(), '_');
    }

    return sanitized;
}

std::string sanitizeDisplayName(const std::string& value)
{
    return value.empty() ? std::string{ "Exported Visage Project" } : value;
}

} // namespace

std::string CMakeEmitter::emitCMakeLists(const model::ProjectDocument& document) const
{
    const std::string projectName = sanitizeProjectNameForCMake(document.projectName);
    std::ostringstream stream;
    stream << "# Generated by VisiForm - Visage Form Builder.\n";
    stream << "# This file is generated.\n";
    stream << "# Manual changes may be overwritten.\n\n";
    stream << "cmake_minimum_required(VERSION 3.24)\n";
    stream << "project(" << projectName << " VERSION 0.1.0 LANGUAGES CXX)\n\n";
    stream << "set(CMAKE_CXX_STANDARD 20)\n";
    stream << "set(CMAKE_CXX_STANDARD_REQUIRED ON)\n";
    stream << "set(CMAKE_CXX_EXTENSIONS OFF)\n\n";
    stream << "if (MSVC)\n";
    stream << "    set(CMAKE_MSVC_RUNTIME_LIBRARY \"MultiThreaded$<$<CONFIG:Debug>:Debug>\")\n";
    stream << "endif()\n\n";
    stream << "include(FetchContent)\n\n";
    stream << "set(VISAGE_BUILD_EXAMPLES OFF CACHE BOOL \"\" FORCE)\n";
    stream << "set(VISAGE_BUILD_TESTS OFF CACHE BOOL \"\" FORCE)\n";
    stream << "set(VISAGE_ENABLE_WIDGETS ON CACHE BOOL \"\" FORCE)\n";
    stream << "set(VISAGE_AMALGAMATED_BUILD ON CACHE BOOL \"\" FORCE)\n\n";
    stream << "FetchContent_Declare(\n";
    stream << "    visage\n";
    stream << "    GIT_REPOSITORY https://github.com/VitalAudio/visage.git\n";
    stream << "    GIT_TAG main\n";
    stream << "    GIT_SHALLOW TRUE\n";
    stream << ")\n\n";
    stream << "FetchContent_MakeAvailable(visage)\n\n";
    stream << "add_executable(" << projectName << "\n";
    stream << "    src/main.cpp\n";
    stream << "    src/MainWindow.cpp\n";
    stream << ")\n\n";
    stream << "target_include_directories(" << projectName << " PRIVATE src)\n\n";
    stream << "target_link_libraries(" << projectName << " PRIVATE visage)\n\n";
    stream << "if (MSVC)\n";
    stream << "    target_compile_options(" << projectName << " PRIVATE /W4 /permissive-)\n";
    stream << "endif()\n\n";
    stream << "# TODO: Generated project may later support vcpkg manifest mode if needed.\n";
    return stream.str();
}

std::string CMakeEmitter::emitCMakePresets() const
{
    std::ostringstream stream;
    stream << "{\n";
    stream << "  \"version\": 6,\n";
    stream << "  \"cmakeMinimumRequired\": {\n";
    stream << "    \"major\": 3,\n";
    stream << "    \"minor\": 24,\n";
    stream << "    \"patch\": 0\n";
    stream << "  },\n";
    stream << "  \"configurePresets\": [\n";
    stream << "    {\n";
    stream << "      \"name\": \"vs2022-x64-static-debug\",\n";
    stream << "      \"displayName\": \"VS2022 x64 Static Debug\",\n";
    stream << "      \"generator\": \"Ninja\",\n";
    stream << "      \"binaryDir\": \"${sourceDir}/build/vs2022-x64-static-debug\",\n";
    stream << "      \"cacheVariables\": {\n";
    stream << "        \"CMAKE_BUILD_TYPE\": \"Debug\",\n";
    stream << "        \"CMAKE_MSVC_RUNTIME_LIBRARY\": \"MultiThreadedDebug\"\n";
    stream << "      }\n";
    stream << "    },\n";
    stream << "    {\n";
    stream << "      \"name\": \"vs2022-x64-static-release\",\n";
    stream << "      \"displayName\": \"VS2022 x64 Static Release\",\n";
    stream << "      \"generator\": \"Ninja\",\n";
    stream << "      \"binaryDir\": \"${sourceDir}/build/vs2022-x64-static-release\",\n";
    stream << "      \"cacheVariables\": {\n";
    stream << "        \"CMAKE_BUILD_TYPE\": \"Release\",\n";
    stream << "        \"CMAKE_MSVC_RUNTIME_LIBRARY\": \"MultiThreaded\"\n";
    stream << "      }\n";
    stream << "    }\n";
    stream << "  ],\n";
    stream << "  \"buildPresets\": [\n";
    stream << "    {\n";
    stream << "      \"name\": \"build-static-debug\",\n";
    stream << "      \"displayName\": \"Build Static Debug\",\n";
    stream << "      \"configurePreset\": \"vs2022-x64-static-debug\"\n";
    stream << "    },\n";
    stream << "    {\n";
    stream << "      \"name\": \"build-static-release\",\n";
    stream << "      \"displayName\": \"Build Static Release\",\n";
    stream << "      \"configurePreset\": \"vs2022-x64-static-release\"\n";
    stream << "    }\n";
    stream << "  ]\n";
    stream << "}\n";
    return stream.str();
}

std::string CMakeEmitter::emitReadme(const model::ProjectDocument& document) const
{
    const std::string projectName = sanitizeDisplayName(document.projectName);
    std::ostringstream stream;
    stream << "# " << projectName << "\n\n";
    stream << "Generated by VisiForm - Visage Form Builder.\n\n";
    stream << "## Requirements\n\n";
    stream << "- Visual Studio 2022\n";
    stream << "- Desktop development with C++\n";
    stream << "- CMake\n";
    stream << "- Ninja\n";
    stream << "- Git\n\n";
    stream << "## Configure Debug\n\n";
    stream << "`cmake --preset vs2022-x64-static-debug`\n\n";
    stream << "## Build Debug\n\n";
    stream << "`cmake --build --preset build-static-debug`\n\n";
    stream << "## Configure Release\n\n";
    stream << "`cmake --preset vs2022-x64-static-release`\n\n";
    stream << "## Build Release\n\n";
    stream << "`cmake --build --preset build-static-release`\n\n";
    stream << "## Open in Visual Studio\n\n";
    stream << "Use `File > Open > Folder` and choose this exported project directory.\n\n";
    stream << "## Known limitations\n\n";
    stream << "- Generated UI is currently static rendering\n";
    stream << "- No generated event handlers yet\n";
    stream << "- No generated native layout manager yet\n";
    stream << "- Visage commit is not pinned yet\n";
    return stream.str();
}

std::string CMakeEmitter::emitGitIgnore() const
{
    return
        "build/\n"
        "out/\n"
        ".vs/\n"
        "CMakeCache.txt\n"
        "CMakeFiles/\n"
        "cmake_install.cmake\n"
        "compile_commands.json\n"
        "logs/\n"
        "*.log\n"
        "*.user\n"
        "*.suo\n"
        ".DS_Store\n"
        "Thumbs.db\n";
}

std::string CMakeEmitter::emitConfigureScript(bool release) const
{
    const char* presetName = release ? "vs2022-x64-static-release" : "vs2022-x64-static-debug";
    std::ostringstream stream;
    stream << "@echo off\r\n";
    stream << "cmake --preset " << presetName << "\r\n";
    return stream.str();
}

std::string CMakeEmitter::emitBuildScript(bool release) const
{
    const char* presetName = release ? "build-static-release" : "build-static-debug";
    std::ostringstream stream;
    stream << "@echo off\r\n";
    stream << "cmake --build --preset " << presetName << "\r\n";
    return stream.str();
}

} // namespace visiform::generator
