#include "generator/CMakeEmitter.h"
#include "generator/CMakeEmitter.h"

#include "utils/FileUtils.h"

#include <algorithm>
#include <cctype>
#include <sstream>

namespace visiform::generator {
namespace {

std::string sanitizeProjectNameForCMake(const std::string& value)
{
    const std::string source = value.empty() ? std::string{"VisiFormProject"} : value;
    std::string sanitized;
    sanitized.reserve(source.size());
    for (char character : source) {
        if (std::isalnum(static_cast<unsigned char>(character)) != 0) {
            sanitized.push_back(character);
        }
        else if (character == '_' || character == '-' || std::isspace(static_cast<unsigned char>(character)) != 0) {
            sanitized.push_back('_');
        }
    }

    if (sanitized.empty()) {
        return "VisiFormProject";
    }
    if (std::isdigit(static_cast<unsigned char>(sanitized.front())) != 0) {
        sanitized.insert(sanitized.begin(), '_');
    }

    return sanitized;
}

std::string sanitizeExecutableName(const std::string& value, const std::string& fallback)
{
    const std::string source = value.empty() ? fallback : value;
    std::string sanitized;
    sanitized.reserve(source.size());
    for (char character : source) {
        if (std::isalnum(static_cast<unsigned char>(character)) != 0 || character == '_' || character == '-') {
            sanitized.push_back(character);
        }
        else {
            sanitized.push_back('_');
        }
    }

    if (sanitized.empty()) {
        sanitized = fallback.empty() ? std::string{"VisiFormProject"} : fallback;
    }
    if (std::isdigit(static_cast<unsigned char>(sanitized.front())) != 0) {
        sanitized.insert(sanitized.begin(), '_');
    }

    return sanitized;
}

std::string sanitizeDisplayName(const std::string& value)
{
    return value.empty() ? std::string{ "VisiFormProject" } : value;
}

std::string sanitizeClassName(const std::string& value, const std::string& fallback)
{
    std::string sanitized;
    for (char character : value.empty() ? fallback : value) {
        if (std::isalnum(static_cast<unsigned char>(character)) != 0 || character == '_') {
            sanitized.push_back(character);
        }
    }
    if (sanitized.empty()) {
        return fallback;
    }
    if (sanitized == "MainWindow" && fallback != "MainWindow") {
        return fallback;
    }
    return sanitized;
}

std::string escapeCMakeString(const std::string& value)
{
    std::string escaped;
    escaped.reserve(value.size());
    for (char character : value) {
        if (character == '\\' || character == '"') {
            escaped.push_back('\\');
        }
        escaped.push_back(character);
    }

    return escaped;
}

std::string escapeJsonString(const std::string& value)
{
    std::ostringstream stream;
    for (unsigned char character : value) {
        switch (character) {
        case '\\':
            stream << "\\\\";
            break;
        case '"':
            stream << "\\\"";
            break;
        case '\b':
            stream << "\\b";
            break;
        case '\f':
            stream << "\\f";
            break;
        case '\n':
            stream << "\\n";
            break;
        case '\r':
            stream << "\\r";
            break;
        case '\t':
            stream << "\\t";
            break;
        default:
            stream << static_cast<char>(character);
            break;
        }
    }

    return stream.str();
}

std::string configuredVisageGitRepository(const utils::AppSettings& settings)
{
    return settings.visageGitRepository.empty()
        ? std::string{ utils::AppSettings::defaultVisageGitRepository }
        : settings.visageGitRepository;
}

std::string configuredVisageGitTag(const utils::AppSettings& settings)
{
    return settings.visageGitTag.empty()
        ? std::string{ utils::AppSettings::defaultVisageGitTag }
        : settings.visageGitTag;
}

std::string configuredLocalVisageSourceDirectory(const utils::AppSettings& settings)
{
    return settings.localVisageSourceDirectory.empty()
        ? std::string{}
        : utils::FileUtils::normalizeSeparators(settings.localVisageSourceDirectory.string());
}

} // namespace

std::string CMakeEmitter::emitCMakeLists(const model::ProjectDocument& document, const utils::AppSettings& settings) const
{
    const std::string projectName = sanitizeProjectNameForCMake(document.projectName);
    const std::string executableName = sanitizeExecutableName(document.executableName, projectName);
    const std::string baseClassName = "MainWindow";
    const std::string userClassName = sanitizeClassName(document.userSubclassName.empty() ? document.mainFormClassName : document.userSubclassName, "AppMainWindow");
    const std::string visageGitRepository = configuredVisageGitRepository(settings);
    const std::string visageGitTag = configuredVisageGitTag(settings);
    std::ostringstream stream;
    stream << "# Generated by VisiForm - Visage Form Builder.\n";
    stream << "# This file is generated.\n";
    stream << "# Manual changes may be overwritten.\n\n";
    stream << "cmake_minimum_required(VERSION 3.24)\n";
    stream << "project(" << projectName << " VERSION 0.1.0 LANGUAGES CXX)\n\n";
    stream << "set(CMAKE_CXX_STANDARD 20)\n";
    stream << "set(CMAKE_CXX_STANDARD_REQUIRED ON)\n";
    stream << "set(CMAKE_CXX_EXTENSIONS OFF)\n\n";
    stream << "if (MSVC)\n";
    stream << "    set(CMAKE_MSVC_RUNTIME_LIBRARY \"MultiThreaded$<$<CONFIG:Debug>:Debug>\")\n";
    stream << "endif()\n\n";
    stream << "include(FetchContent)\n\n";
    stream << "set(VISIFORM_VISAGE_SOURCE_DIR \"\" CACHE PATH \"Optional local Visage source directory\")\n";
    stream << "set(VISIFORM_VISAGE_GIT_REPOSITORY \"" << escapeCMakeString(visageGitRepository) << "\" CACHE STRING \"Visage Git repository\")\n";
    stream << "set(VISIFORM_VISAGE_GIT_TAG \"" << escapeCMakeString(visageGitTag) << "\" CACHE STRING \"Visage Git tag or commit\")\n\n";
    stream << "set(VISAGE_BUILD_EXAMPLES OFF CACHE BOOL \"\" FORCE)\n";
    stream << "set(VISAGE_BUILD_TESTS OFF CACHE BOOL \"\" FORCE)\n";
    stream << "set(VISAGE_ENABLE_WIDGETS ON CACHE BOOL \"\" FORCE)\n";
    stream << "set(VISAGE_AMALGAMATED_BUILD ON CACHE BOOL \"\" FORCE)\n\n";
    stream << "if (VISIFORM_VISAGE_SOURCE_DIR AND EXISTS \"${VISIFORM_VISAGE_SOURCE_DIR}/CMakeLists.txt\")\n";
    stream << "    message(STATUS \"Using local Visage source: ${VISIFORM_VISAGE_SOURCE_DIR}\")\n\n";
    stream << "    add_subdirectory(\n";
    stream << "        \"${VISIFORM_VISAGE_SOURCE_DIR}\"\n";
    stream << "        \"${CMAKE_BINARY_DIR}/_deps/visage-build\"\n";
    stream << "    )\n";
    stream << "else()\n";
    stream << "    message(STATUS \"Using FetchContent Visage fallback\")\n";
    stream << "    message(STATUS \"Visage repository: ${VISIFORM_VISAGE_GIT_REPOSITORY}\")\n";
    stream << "    message(STATUS \"Visage tag/commit: ${VISIFORM_VISAGE_GIT_TAG}\")\n\n";
    stream << "    FetchContent_Declare(\n";
    stream << "        visage\n";
    stream << "        GIT_REPOSITORY \"${VISIFORM_VISAGE_GIT_REPOSITORY}\"\n";
    stream << "        GIT_TAG \"${VISIFORM_VISAGE_GIT_TAG}\"\n";
    stream << "        GIT_SHALLOW TRUE\n";
    stream << "    )\n\n";
    stream << "    FetchContent_MakeAvailable(visage)\n";
    stream << "endif()\n\n";
    stream << "add_executable(" << executableName << "\n";
    stream << "    src/main.cpp\n";
    stream << "    src/" << baseClassName << ".cpp\n";
    stream << "    src/" << userClassName << ".cpp\n";
    stream << ")\n\n";
    stream << "target_include_directories(" << executableName << " PRIVATE src)\n\n";
    stream << "target_link_libraries(" << executableName << " PRIVATE visage)\n\n";
    stream << "if (MSVC)\n";
    stream << "    target_compile_options(" << executableName << " PRIVATE /W4 /permissive-)\n";
    stream << "endif()\n\n";
    stream << "# TODO: Generated project may later support vcpkg manifest mode if needed.\n";
    return stream.str();
}

std::string CMakeEmitter::emitCMakePresets(const utils::AppSettings& settings) const
{
    const std::string localVisageSourceDirectory = configuredLocalVisageSourceDirectory(settings);
    std::ostringstream stream;
    stream << "{\n";
    stream << "  \"version\": 6,\n";
    stream << "  \"cmakeMinimumRequired\": {\n";
    stream << "    \"major\": 3,\n";
    stream << "    \"minor\": 24,\n";
    stream << "    \"patch\": 0\n";
    stream << "  },\n";
    stream << "  \"configurePresets\": [\n";
    stream << "    {\n";
    stream << "      \"name\": \"vs2022-x64-static-debug\",\n";
    stream << "      \"displayName\": \"VS2022 x64 Static Debug\",\n";
    stream << "      \"generator\": \"Ninja\",\n";
    stream << "      \"binaryDir\": \"${sourceDir}/build/vs2022-x64-static-debug\",\n";
    stream << "      \"cacheVariables\": {\n";
    stream << "        \"CMAKE_BUILD_TYPE\": \"Debug\",\n";
    stream << "        \"CMAKE_MSVC_RUNTIME_LIBRARY\": \"MultiThreadedDebug\"";
    if (!localVisageSourceDirectory.empty()) {
        stream << ",\n";
        stream << "        \"VISIFORM_VISAGE_SOURCE_DIR\": \"" << escapeJsonString(localVisageSourceDirectory) << "\"\n";
    }
    else {
        stream << "\n";
    }
    stream << "      }\n";
    stream << "    },\n";
    stream << "    {\n";
    stream << "      \"name\": \"vs2022-x64-static-release\",\n";
    stream << "      \"displayName\": \"VS2022 x64 Static Release\",\n";
    stream << "      \"generator\": \"Ninja\",\n";
    stream << "      \"binaryDir\": \"${sourceDir}/build/vs2022-x64-static-release\",\n";
    stream << "      \"cacheVariables\": {\n";
    stream << "        \"CMAKE_BUILD_TYPE\": \"Release\",\n";
    stream << "        \"CMAKE_MSVC_RUNTIME_LIBRARY\": \"MultiThreaded\"";
    if (!localVisageSourceDirectory.empty()) {
        stream << ",\n";
        stream << "        \"VISIFORM_VISAGE_SOURCE_DIR\": \"" << escapeJsonString(localVisageSourceDirectory) << "\"\n";
    }
    else {
        stream << "\n";
    }
    stream << "      }\n";
    stream << "    }\n";
    stream << "  ],\n";
    stream << "  \"buildPresets\": [\n";
    stream << "    {\n";
    stream << "      \"name\": \"build-static-debug\",\n";
    stream << "      \"displayName\": \"Build Static Debug\",\n";
    stream << "      \"configurePreset\": \"vs2022-x64-static-debug\"\n";
    stream << "    },\n";
    stream << "    {\n";
    stream << "      \"name\": \"build-static-release\",\n";
    stream << "      \"displayName\": \"Build Static Release\",\n";
    stream << "      \"configurePreset\": \"vs2022-x64-static-release\"\n";
    stream << "    }\n";
    stream << "  ]\n";
    stream << "}\n";
    return stream.str();
}

std::string CMakeEmitter::emitReadme(const model::ProjectDocument& document, const utils::AppSettings& settings) const
{
    const std::string projectName = sanitizeDisplayName(document.projectName);
    const std::string executableName = sanitizeExecutableName(document.executableName, sanitizeProjectNameForCMake(document.projectName));
    const std::string baseClassName = "MainWindow";
    const std::string userClassName = sanitizeClassName(document.userSubclassName.empty() ? document.mainFormClassName : document.userSubclassName, "AppMainWindow");
    const std::string localVisageSourceDirectory = configuredLocalVisageSourceDirectory(settings);
    std::ostringstream stream;
    stream << "# " << projectName << "\n\n";
    stream << "Generated by VisiForm - Visage Form Builder.\n\n";
    stream << "## Requirements\n\n";
    stream << "- Visual Studio 2022\n";
    stream << "- Desktop development with C++\n";
    stream << "- CMake\n";
    stream << "- Ninja\n";
    stream << "- Git\n\n";
    stream << "## Visage dependency modes\n\n";
    stream << "### Fast local source mode\n\n";
    stream << "Set `VISIFORM_VISAGE_SOURCE_DIR` to a local Visage checkout, for example `J:/Dev/CeePlusPlus/visage`.\n\n";
    if (!localVisageSourceDirectory.empty()) {
        stream << "This export was generated with `VISIFORM_VISAGE_SOURCE_DIR` configured in `CMakePresets.json` as `" << localVisageSourceDirectory << "`.\n\n";
    }
    stream << "### Portable fallback\n\n";
    stream << "If `VISIFORM_VISAGE_SOURCE_DIR` is empty or does not point to a valid Visage source tree, CMake falls back to `FetchContent` using the configured repository and tag values.\n\n";
    stream << "## Debug build\n\n";
    stream << "`cmake --preset vs2022-x64-static-debug`\n\n";
    stream << "`cmake --build --preset build-static-debug`\n\n";
    stream << "## Release build\n\n";
    stream << "`cmake --preset vs2022-x64-static-release`\n\n";
    stream << "`cmake --build --preset build-static-release`\n\n";
    stream << "## Open in Visual Studio\n\n";
    stream << "Use `File > Open > Folder` and choose this exported project directory.\n\n";
    stream << "Select the `vs2022-x64-static-debug` or `vs2022-x64-static-release` preset in Visual Studio, then build and run from the IDE.\n\n";
    stream << "## Generated source structure\n\n";
    stream << "- `src/" << baseClassName << ".*` is regenerated by VisiForm\n";
    stream << "- `src/" << userClassName << ".*` is the user subclass layer\n";
    stream << "- Put custom logic in `src/" << userClassName << ".cpp` USER CODE regions\n\n";
    stream << "## Generated executable\n\n";
    stream << "- CMake project name: `" << sanitizeProjectNameForCMake(document.projectName) << "`\n";
    stream << "- Executable target name: `" << executableName << "`\n";
    stream << "- Produced executable: `" << executableName << ".exe` on Windows\n\n";
    stream << "## Debug and release notes\n\n";
    stream << "- Debug uses the `vs2022-x64-static-debug` configure preset and `build-static-debug` build preset\n";
    stream << "- Release uses the `vs2022-x64-static-release` configure preset and `build-static-release` build preset\n\n";
    stream << "## Known limitations\n\n";
    stream << "- Generated UI interaction is intentionally lightweight and not a full retained-mode widget toolkit\n";
    stream << "- Runtime theme switching is future work\n";
    stream << "- Color picker interaction is still minimal\n";
    stream << "- No generated native layout manager yet\n";
    stream << "- Visage commit is not pinned yet\n";
    return stream.str();
}

std::string CMakeEmitter::emitGitIgnore() const
{
    return
        "build/\n"
        "out/\n"
        ".vs/\n"
        "CMakeCache.txt\n"
        "CMakeFiles/\n"
        "cmake_install.cmake\n"
        "compile_commands.json\n"
        "logs/\n"
        "*.log\n"
        "*.user\n"
        "*.suo\n"
        ".DS_Store\n"
        "Thumbs.db\n";
}

std::string CMakeEmitter::emitConfigureScript(bool release) const
{
    const char* presetName = release ? "vs2022-x64-static-release" : "vs2022-x64-static-debug";
    std::ostringstream stream;
    stream << "@echo off\r\n";
    stream << "cmake --preset " << presetName << "\r\n";
    return stream.str();
}

std::string CMakeEmitter::emitBuildScript(bool release) const
{
    const char* presetName = release ? "build-static-release" : "build-static-debug";
    std::ostringstream stream;
    stream << "@echo off\r\n";
    stream << "cmake --build --preset " << presetName << "\r\n";
    return stream.str();
}

} // namespace visiform::generator
