#include "generator/CMakeEmitter.h"

#include "generator/CMakeEmitter.h"

#include <algorithm>
#include <cctype>
#include <sstream>

namespace visiform::generator {
namespace {

std::string sanitizeProjectNameForCMake(const std::string& value)
{
    std::string sanitized;
    sanitized.reserve(value.size());
    for (char character : value) {
        if (std::isalnum(static_cast<unsigned char>(character)) != 0) {
            sanitized.push_back(character);
        }
        else if (character == '_' || character == '-') {
            sanitized.push_back('_');
        }
    }

    if (sanitized.empty()) {
        return "ExportedVisageProject";
    }
    if (std::isdigit(static_cast<unsigned char>(sanitized.front())) != 0) {
        sanitized.insert(sanitized.begin(), '_');
    }

    return sanitized;
}

} // namespace

std::string CMakeEmitter::emitCMakeLists(const model::ProjectDocument& document) const
{
    const std::string projectName = sanitizeProjectNameForCMake(document.projectName);
    std::ostringstream stream;
    stream << "# Generated by VisiForm - Visage Form Builder.\n";
    stream << "# This file is generated.\n";
    stream << "# Manual changes may be overwritten.\n\n";
    stream << "cmake_minimum_required(VERSION 3.24)\n";
    stream << "project(" << projectName << " VERSION 0.1.0 LANGUAGES CXX)\n\n";
    stream << "set(CMAKE_CXX_STANDARD 20)\n";
    stream << "set(CMAKE_CXX_STANDARD_REQUIRED ON)\n";
    stream << "set(CMAKE_CXX_EXTENSIONS OFF)\n\n";
    stream << "if (MSVC)\n";
    stream << "    set(CMAKE_MSVC_RUNTIME_LIBRARY \"MultiThreaded$<$<CONFIG:Debug>:Debug>\")\n";
    stream << "endif()\n\n";
    stream << "include(FetchContent)\n\n";
    stream << "set(VISAGE_BUILD_EXAMPLES OFF CACHE BOOL \"\" FORCE)\n";
    stream << "set(VISAGE_BUILD_TESTS OFF CACHE BOOL \"\" FORCE)\n";
    stream << "set(VISAGE_ENABLE_WIDGETS ON CACHE BOOL \"\" FORCE)\n";
    stream << "set(VISAGE_AMALGAMATED_BUILD ON CACHE BOOL \"\" FORCE)\n\n";
    stream << "FetchContent_Declare(\n";
    stream << "    visage\n";
    stream << "    GIT_REPOSITORY https://github.com/VitalAudio/visage.git\n";
    stream << "    GIT_TAG main\n";
    stream << "    GIT_SHALLOW TRUE\n";
    stream << ")\n\n";
    stream << "FetchContent_MakeAvailable(visage)\n\n";
    stream << "add_executable(" << projectName << "\n";
    stream << "    src/main.cpp\n";
    stream << "    src/MainWindow.cpp\n";
    stream << ")\n\n";
    stream << "target_include_directories(" << projectName << " PRIVATE src)\n\n";
    stream << "target_link_libraries(" << projectName << " PRIVATE visage)\n\n";
    stream << "if (MSVC)\n";
    stream << "    target_compile_options(" << projectName << " PRIVATE /W4 /permissive-)\n";
    stream << "endif()\n\n";
    stream << "# TODO: Generated project may later support vcpkg manifest mode if needed.\n";
    return stream.str();
}

} // namespace visiform::generator
