#include "generator/VisageCppEmitter.h"

#include "generator/VisageCppEmitter.h"

#include <algorithm>
#include <cctype>
#include <iomanip>
#include <sstream>

namespace visiform::generator {
namespace {

constexpr const char* kGeneratedFileHeader =
    "// Generated by VisiForm - Visage Form Builder.\n"
    "// This file is generated.\n"
    "// Manual changes may be overwritten.\n\n";

std::string sanitizeCppIdentifier(const std::string& value)
{
    std::string sanitized;
    sanitized.reserve(value.size());
    for (char character : value) {
        if (std::isalnum(static_cast<unsigned char>(character)) != 0 || character == '_') {
            sanitized.push_back(character);
        }
        else {
            sanitized.push_back('_');
        }
    }

    if (sanitized.empty()) {
        return "GeneratedIdentifier";
    }
    if (std::isdigit(static_cast<unsigned char>(sanitized.front())) != 0) {
        sanitized.insert(sanitized.begin(), '_');
    }

    return sanitized;
}

std::string sanitizeClassName(const std::string& value)
{
    std::string sanitized = sanitizeCppIdentifier(value);
    if (!sanitized.empty() && std::islower(static_cast<unsigned char>(sanitized.front())) != 0) {
        sanitized.front() = static_cast<char>(std::toupper(static_cast<unsigned char>(sanitized.front())));
    }
    return sanitized;
}

std::string escapeCppStringLiteral(const std::string& value)
{
    std::ostringstream stream;
    for (char character : value) {
        switch (character) {
        case '\\': stream << "\\\\"; break;
        case '"': stream << "\\\""; break;
        case '\n': stream << "\\n"; break;
        case '\r': stream << "\\r"; break;
        case '\t': stream << "\\t"; break;
        default: stream << character; break;
        }
    }
    return stream.str();
}

std::string emitFloat(float value)
{
    std::ostringstream stream;
    stream << std::fixed << std::setprecision(2) << value << 'f';
    return stream.str();
}

std::string emitStringLiteral(const std::string& value)
{
    return std::string{"\""} + escapeCppStringLiteral(value) + "\"";
}

std::string emitColorExpression(const std::string& value, const std::string& defaultColorLiteral)
{
    if (value.size() == 7 && value.front() == '#') {
        std::string digits = value.substr(1);
        std::transform(digits.begin(), digits.end(), digits.begin(),
            [](unsigned char character) { return static_cast<char>(std::toupper(character)); });
        return "0xff" + digits;
    }
    if (value.size() == 9 && value.front() == '#') {
        std::string digits = value.substr(1);
        std::transform(digits.begin(), digits.end(), digits.begin(),
            [](unsigned char character) { return static_cast<char>(std::toupper(character)); });
        return "0x" + digits;
    }

    return defaultColorLiteral;
}

std::string widgetLabel(const visiform::model::WidgetNode& widget)
{
    if (!widget.name.empty()) {
        return widget.name;
    }
    if (!widget.id.empty()) {
        return widget.id;
    }

    return widget.typeName();
}

void emitWidgetDraw(std::ostringstream& stream,
    const visiform::model::WidgetNode& widget,
    float parentX,
    float parentY,
    int indentLevel)
{
    const std::string indent(indentLevel * 4, ' ');
    const std::string xExpr = emitFloat(parentX + widget.bounds.x);
    const std::string yExpr = emitFloat(parentY + widget.bounds.y);
    const std::string widthExpr = emitFloat(widget.bounds.width);
    const std::string heightExpr = emitFloat(widget.bounds.height);

    switch (widget.type) {
    case visiform::model::WidgetType::FormWindow:
        stream << indent << "canvas.setColor(" << emitColorExpression(widget.getStringProperty("backgroundColor", "#ECEFF5"), "0xffECEFF5") << ");\n";
        stream << indent << "canvas.fill(" << xExpr << ", " << yExpr << ", " << widthExpr << ", " << heightExpr << ");\n";
        stream << indent << "canvas.setColor(0xffC0C8D5);\n";
        stream << indent << "canvas.fill(" << xExpr << ", " << yExpr << ", " << widthExpr << ", 28.0f);\n";
        stream << indent << "drawBorder(canvas, " << xExpr << ", " << yExpr << ", " << widthExpr << ", " << heightExpr << ", 0xff6C7788);\n";
        stream << indent << "if (drawText) {\n";
        stream << indent << "    canvas.setColor(0xff243041);\n";
        stream << indent << "    canvas.text(" << emitStringLiteral(widget.getStringProperty("title", widgetLabel(widget)))
               << ", labelFont_, visage::Font::kTopLeft, " << xExpr << " + 10.0f, " << yExpr << " + 4.0f, " << widthExpr << " - 20.0f, 22.0f);\n";
        stream << indent << "}\n";
        break;
    case visiform::model::WidgetType::Frame:
        stream << indent << "canvas.setColor(" << emitColorExpression(widget.getStringProperty("backgroundColor", "#D9DEE8"), "0xffD9DEE8") << ");\n";
        stream << indent << "canvas.fill(" << xExpr << ", " << yExpr << ", " << widthExpr << ", " << heightExpr << ");\n";
        stream << indent << "drawBorder(canvas, " << xExpr << ", " << yExpr << ", " << widthExpr << ", " << heightExpr << ", 0xff97A3B7);\n";
        stream << indent << "if (drawText) {\n";
        stream << indent << "    canvas.setColor(0xff243041);\n";
        stream << indent << "    canvas.text(" << emitStringLiteral(widget.getStringProperty("title", widgetLabel(widget)))
               << ", labelFont_, visage::Font::kTopLeft, " << xExpr << " + 8.0f, " << yExpr << " + 6.0f, " << widthExpr << " - 16.0f, 20.0f);\n";
        stream << indent << "}\n";
        break;
    case visiform::model::WidgetType::Label:
        stream << indent << "if (drawText) {\n";
        stream << indent << "    canvas.setColor(0xff1F2530);\n";
        stream << indent << "    canvas.text(" << emitStringLiteral(widget.getStringProperty("text", widgetLabel(widget)))
               << ", labelFont_, visage::Font::kTopLeft, " << xExpr << ", " << yExpr << " + 2.0f, " << widthExpr << ", " << heightExpr << ");\n";
        stream << indent << "}\n";
        break;
    case visiform::model::WidgetType::Button:
        stream << indent << "canvas.setColor(0xffEBEDF2);\n";
        stream << indent << "canvas.fill(" << xExpr << ", " << yExpr << ", " << widthExpr << ", " << heightExpr << ");\n";
        stream << indent << "drawBorder(canvas, " << xExpr << ", " << yExpr << ", " << widthExpr << ", " << heightExpr << ", 0xffCCD2DC);\n";
        stream << indent << "// TODO: Add button event handler for " << sanitizeCppIdentifier(widget.id) << "\n";
        stream << indent << "if (drawText) {\n";
        stream << indent << "    canvas.setColor(0xff1F2530);\n";
        stream << indent << "    canvas.text(" << emitStringLiteral(widget.getStringProperty("text", widgetLabel(widget)))
               << ", labelFont_, visage::Font::kCenter, " << xExpr << ", " << yExpr << ", " << widthExpr << ", " << heightExpr << ");\n";
        stream << indent << "}\n";
        break;
    case visiform::model::WidgetType::TextBox:
        stream << indent << "canvas.setColor(0xffffffff);\n";
        stream << indent << "canvas.fill(" << xExpr << ", " << yExpr << ", " << widthExpr << ", " << heightExpr << ");\n";
        stream << indent << "drawBorder(canvas, " << xExpr << ", " << yExpr << ", " << widthExpr << ", " << heightExpr << ", 0xffB9C2D0);\n";
        stream << indent << "if (drawText) {\n";
        stream << indent << "    canvas.setColor(0xff586275);\n";
        stream << indent << "    canvas.text(" << emitStringLiteral(widget.getStringProperty("text", ""))
               << ", labelFont_, visage::Font::kTopLeft, " << xExpr << " + 8.0f, " << yExpr << " + 6.0f, " << widthExpr << " - 12.0f, " << heightExpr << " - 8.0f);\n";
        stream << indent << "}\n";
        break;
    case visiform::model::WidgetType::CheckBox:
        stream << indent << "canvas.setColor(0xffffffff);\n";
        stream << indent << "canvas.fill(" << xExpr << ", " << yExpr << " + (" << heightExpr << " - 18.0f) * 0.5f, 18.0f, 18.0f);\n";
        stream << indent << "drawBorder(canvas, " << xExpr << ", " << yExpr << " + (" << heightExpr << " - 18.0f) * 0.5f, 18.0f, 18.0f, 0xff8390A4);\n";
        if (widget.getBoolProperty("checked", false)) {
            stream << indent << "canvas.setColor(0xff2D7FF9);\n";
            stream << indent << "canvas.fill(" << xExpr << " + 4.0f, " << yExpr << " + (" << heightExpr << " - 10.0f) * 0.5f, 10.0f, 10.0f);\n";
        }
        stream << indent << "if (drawText) {\n";
        stream << indent << "    canvas.setColor(0xff1F2530);\n";
        stream << indent << "    canvas.text(" << emitStringLiteral(widget.getStringProperty("text", widgetLabel(widget)))
               << ", labelFont_, visage::Font::kTopLeft, " << xExpr << " + 26.0f, " << yExpr << " + 4.0f, " << widthExpr << " - 26.0f, " << heightExpr << " - 6.0f);\n";
        stream << indent << "}\n";
        break;
    case visiform::model::WidgetType::Slider: {
        const float minValue = widget.getFloatProperty("min", 0.0f);
        const float maxValue = widget.getFloatProperty("max", 100.0f);
        const float currentValue = widget.getFloatProperty("value", 50.0f);
        const float denominator = maxValue > minValue ? (maxValue - minValue) : 1.0f;
        const float normalized = std::clamp((currentValue - minValue) / denominator, 0.0f, 1.0f);
        stream << indent << "canvas.setColor(0xff98A3B3);\n";
        stream << indent << "canvas.fill(" << xExpr << " + 8.0f, " << yExpr << " + " << heightExpr << " * 0.5f - 2.0f, " << widthExpr << " - 16.0f, 4.0f);\n";
        stream << indent << "canvas.setColor(0xff2D7FF9);\n";
        stream << indent << "canvas.fill(" << xExpr << " + 8.0f + (" << widthExpr << " - 28.0f) * " << emitFloat(normalized)
               << ", " << yExpr << " + " << heightExpr << " * 0.5f - 8.0f, 12.0f, 16.0f);\n";
        break;
    }
    case visiform::model::WidgetType::Image:
        stream << indent << "canvas.setColor(0xffD3DAE6);\n";
        stream << indent << "canvas.fill(" << xExpr << ", " << yExpr << ", " << widthExpr << ", " << heightExpr << ");\n";
        stream << indent << "drawBorder(canvas, " << xExpr << ", " << yExpr << ", " << widthExpr << ", " << heightExpr << ", 0xff98A3B3);\n";
        stream << indent << "if (drawText) {\n";
        stream << indent << "    canvas.setColor(0xff4E596C);\n";
        stream << indent << "    canvas.text(" << emitStringLiteral(widget.getStringProperty("source", widgetLabel(widget)))
               << ", labelFont_, visage::Font::kCenter, " << xExpr << ", " << yExpr << ", " << widthExpr << ", " << heightExpr << ");\n";
        stream << indent << "}\n";
        break;
    case visiform::model::WidgetType::Spacer:
        stream << indent << "drawBorder(canvas, " << xExpr << ", " << yExpr << ", " << widthExpr << ", " << heightExpr << ", 0xff98A3B3);\n";
        stream << indent << "if (drawText) {\n";
        stream << indent << "    canvas.setColor(0xff4E596C);\n";
        stream << indent << "    canvas.text(\"Spacer\", labelFont_, visage::Font::kCenter, " << xExpr << ", " << yExpr << ", " << widthExpr << ", " << heightExpr << ");\n";
        stream << indent << "}\n";
        break;
    }

    for (const auto& child : widget.children) {
        emitWidgetDraw(stream, child, parentX + widget.bounds.x, parentY + widget.bounds.y, indentLevel);
    }
}

std::string emitMainWindowHeader(const visiform::model::ProjectDocument& document)
{
    const std::string className = sanitizeClassName(document.mainFormClassName.empty() ? "MainWindow" : document.mainFormClassName);
    std::ostringstream stream;
    stream << kGeneratedFileHeader;
    stream << "#pragma once\n\n";
    stream << "#include <visage/app.h>\n";
    stream << "#include <visage/graphics.h>\n\n";
    stream << "class " << className << " : public visage::ApplicationWindow {\n";
    stream << "public:\n";
    stream << "    " << className << "();\n";
    stream << "    ~" << className << "() override = default;\n\n";
    stream << "    void showWindow();\n";
    stream << "    void draw(visage::Canvas& canvas) override;\n\n";
    stream << "private:\n";
    stream << "    bool canDrawText() const;\n\n";
    stream << "    visage::Font labelFont_{};\n";
    stream << "};\n";
    return stream.str();
}

std::string emitMainCpp(const visiform::model::ProjectDocument& document)
{
    const std::string className = sanitizeClassName(document.mainFormClassName.empty() ? "MainWindow" : document.mainFormClassName);
    std::ostringstream stream;
    stream << kGeneratedFileHeader;
    stream << "#include \"MainWindow.h\"\n\n";
    stream << "#include <exception>\n";
    stream << "#include <iostream>\n\n";
    stream << "int main()\n";
    stream << "{\n";
    stream << "    try {\n";
    stream << "        " << className << " window;\n";
    stream << "        window.showWindow();\n";
    stream << "        if (!window.isShowing()) {\n";
    stream << "            throw std::runtime_error(\"The generated Visage window did not open.\");\n";
    stream << "        }\n";
    stream << "\n";
    stream << "        window.runEventLoop();\n";
    stream << "        return 0;\n";
    stream << "    }\n";
    stream << "    catch (const std::exception& exception) {\n";
    stream << "        std::cerr << \"Generated Visage project failed to start: \" << exception.what() << '\\n';\n";
    stream << "    }\n";
    stream << "    catch (...) {\n";
    stream << "        std::cerr << \"Generated Visage project failed to start with an unknown error.\\n\";\n";
    stream << "    }\n\n";
    stream << "    return 1;\n";
    stream << "}\n";
    return stream.str();
}

std::string emitMainWindowCpp(const visiform::model::ProjectDocument& document)
{
    const std::string className = sanitizeClassName(document.mainFormClassName.empty() ? "MainWindow" : document.mainFormClassName);
    const std::string windowTitle = document.root.getStringProperty("title", document.mainFormClassName.empty() ? "MainWindow" : document.mainFormClassName);
    const float windowWidth = std::max(1000.0f, document.root.bounds.width + 120.0f);
    const float windowHeight = std::max(800.0f, document.root.bounds.height + 120.0f);

    std::ostringstream stream;
    stream << kGeneratedFileHeader;
    stream << "#include \"MainWindow.h\"\n\n";
    stream << "#include <array>\n";
    stream << "#include <fstream>\n";
    stream << "#include <string>\n\n";
    stream << "namespace {\n\n";
    stream << "void drawBorder(visage::Canvas& canvas, float x, float y, float width, float height, int color, float thickness = 1.0f)\n";
    stream << "{\n";
    stream << "    canvas.setColor(color);\n";
    stream << "    canvas.fill(x, y, width, thickness);\n";
    stream << "    canvas.fill(x, y + height - thickness, width, thickness);\n";
    stream << "    canvas.fill(x, y, thickness, height);\n";
    stream << "    canvas.fill(x + width - thickness, y, thickness, height);\n";
    stream << "}\n\n";
    stream << "} // namespace\n\n";
    stream << className << "::" << className << "()\n";
    stream << "{\n";
    stream << "    setTitle(" << emitStringLiteral(windowTitle) << ");\n";
    stream << "\n";
    stream << "    static constexpr std::array<const char*, 3> kFontCandidates = {\n";
    stream << "        \"C:/Windows/Fonts/segoeui.ttf\",\n";
    stream << "        \"C:/Windows/Fonts/tahoma.ttf\",\n";
    stream << "        \"C:/Windows/Fonts/arial.ttf\"\n";
    stream << "    };\n\n";
    stream << "    for (const char* fontPath : kFontCandidates) {\n";
    stream << "        std::ifstream fontFile(fontPath, std::ios::binary);\n";
    stream << "        if (!fontFile.good()) {\n";
    stream << "            continue;\n";
    stream << "        }\n\n";
    stream << "        labelFont_ = visage::Font(18.0f, std::string{ fontPath });\n";
    stream << "        if (canDrawText()) {\n";
    stream << "            break;\n";
    stream << "        }\n";
    stream << "    }\n";
    stream << "}\n\n";
    stream << "void " << className << "::showWindow()\n";
    stream << "{\n";
    stream << "    show(visage::Dimension::logicalPixels(" << emitFloat(windowWidth) << "), visage::Dimension::logicalPixels(" << emitFloat(windowHeight) << "));\n";
    stream << "}\n\n";
    stream << "void " << className << "::draw(visage::Canvas& canvas)\n";
    stream << "{\n";
    stream << "    canvas.setColor(0xff1B1D23);\n";
    stream << "    canvas.fill(0.0f, 0.0f, width(), height());\n\n";
    stream << "    const bool drawText = canDrawText();\n";
    stream << "    const float formOffsetX = 40.0f;\n";
    stream << "    const float formOffsetY = 60.0f;\n\n";
    emitWidgetDraw(stream, document.root, 40.0f, 60.0f, 1);
    stream << "}\n\n";
    stream << "bool " << className << "::canDrawText() const\n";
    stream << "{\n";
    stream << "    return labelFont_.packedFont() != nullptr;\n";
    stream << "}\n";
    return stream.str();
}

} // namespace

VisageCppEmitter::EmittedSources VisageCppEmitter::emitProjectSources(const model::ProjectDocument& document) const
{
    return {
        emitMainCpp(document),
        emitMainWindowHeader(document),
        emitMainWindowCpp(document)
    };
}

} // namespace visiform::generator
