#include "generator/VisageCppEmitter.h"

#include "generator/VisageCppEmitter.h"

#include "model/LookAndFeelRegistry.h"
#include "utils/CppIdentifier.h"

#include <algorithm>
#include <cctype>
#include <iomanip>
#include <map>
#include <sstream>
#include <unordered_map>
#include <vector>

namespace visiform::generator {
namespace {

constexpr const char* kGeneratedFileHeader =
    "// Generated by VisiForm - Visage Form Builder.\n"
    "// This file is generated.\n"
    "// Manual changes may be overwritten.\n\n";

std::string sanitizeClassName(const std::string& value)
{
    std::string sanitized = utils::sanitizeCppIdentifier(value);
    if (!sanitized.empty() && std::islower(static_cast<unsigned char>(sanitized.front())) != 0) {
        sanitized.front() = static_cast<char>(std::toupper(static_cast<unsigned char>(sanitized.front())));
    }

    return sanitized;
}

std::string generatedBaseClassName(const visiform::model::ProjectDocument& document)
{
    (void)document;
    return "MainWindow";
}

std::string userSubclassName(const visiform::model::ProjectDocument& document)
{
    const std::string fallback = document.userSubclassName.empty()
        ? (document.mainFormClassName.empty() ? "AppMainWindow" : document.mainFormClassName)
        : document.userSubclassName;
    const std::string sanitized = sanitizeClassName(fallback);
    return sanitized.empty() || sanitized == "MainWindow" ? "AppMainWindow" : sanitized;
}

std::string escapeCppStringLiteral(const std::string& value)
{
    std::ostringstream stream;
    for (char character : value) {
        switch (character) {
        case '\\': stream << "\\\\"; break;
        case '"': stream << "\\\""; break;
        case '\n': stream << "\\n"; break;
        case '\r': stream << "\\r"; break;
        case '\t': stream << "\\t"; break;
        default: stream << character; break;
        }
    }
    return stream.str();
}

std::string progressBarDisplayText(const visiform::model::WidgetNode& widget)
{
    if (!widget.getBoolProperty("showText", true)) {
        return {};
    }

    const std::string explicitText = widget.getStringProperty("text", {});
    if (!explicitText.empty()) {
        return explicitText;
    }

    const float minimum = widget.getFloatProperty("min", 0.0f);
    const float maximum = std::max(minimum, widget.getFloatProperty("max", 100.0f));
    const float safeMaximum = maximum <= minimum ? minimum + 1.0f : maximum;
    const float currentValue = std::clamp(widget.getFloatProperty("value", minimum), minimum, safeMaximum);
    const float normalized = safeMaximum <= minimum ? 0.0f : std::clamp((currentValue - minimum) / (safeMaximum - minimum), 0.0f, 1.0f);
    return std::to_string(static_cast<int>(std::round(normalized * 100.0f))) + "%";
}

std::string emitFloat(float value)
{
    std::ostringstream stream;
    stream << std::fixed << std::setprecision(2) << value << 'f';
    return stream.str();
}

std::string emitStringLiteral(const std::string& value)
{
    return std::string{"\""} + escapeCppStringLiteral(value) + "\"";
}

std::string displayTextOrFallback(const visiform::model::WidgetNode& widget, const std::string& key, const std::string& fallback)
{
    const std::string value = widget.getStringProperty(key, {});
    return value.empty() ? fallback : value;
}

std::string emitColorExpression(const std::string& value, const std::string& defaultColorLiteral)
{
    if (value.size() == 7 && value.front() == '#') {
        std::string digits = value.substr(1);
        std::transform(digits.begin(), digits.end(), digits.begin(),
            [](unsigned char character) { return static_cast<char>(std::toupper(character)); });
        return "0xff" + digits;
    }
    if (value.size() == 9 && value.front() == '#') {
        std::string digits = value.substr(1);
        std::transform(digits.begin(), digits.end(), digits.begin(),
            [](unsigned char character) { return static_cast<char>(std::toupper(character)); });
        return "0x" + digits;
    }

    return defaultColorLiteral;
}

struct ResolvedWidgetStyle {
    std::string panelColor;
    std::string fillColor;
    std::string textColor;
    std::string borderColor;
    std::string accentColor;
    std::string disabledColor;
    float borderThickness = 1.0f;
    float cornerRadius = 0.0f;
    float fontSize = 16.0f;
};

ResolvedWidgetStyle resolveWidgetStyle(const visiform::model::ProjectDocument& document, const visiform::model::WidgetNode& widget)
{
    const auto& registry = visiform::model::LookAndFeelRegistry::instance();
    const std::string widgetLookAndFeelId = widget.getStringProperty("lookAndFeelId", {});
    const visiform::model::LookAndFeelDefinition* definition = !widgetLookAndFeelId.empty()
        ? registry.findById(widgetLookAndFeelId)
        : registry.findById(document.lookAndFeelId);
    if (definition == nullptr) {
        definition = &registry.defaultDefinition();
    }

    ResolvedWidgetStyle style{
        definition->panelColor,
        definition->controlFillColor,
        definition->controlTextColor,
        definition->controlBorderColor,
        definition->accentColor,
        definition->disabledColor,
        definition->borderThickness,
        definition->cornerRadius,
        definition->fontSize };

    const std::string fillOverride = widget.getStringProperty("fillColor", {});
    const std::string textOverride = widget.getStringProperty("textColor", {});
    const std::string borderOverride = widget.getStringProperty("borderColor", {});
    const std::string accentOverride = widget.getStringProperty("accentColor", {});
    if (!fillOverride.empty()) {
        style.fillColor = fillOverride;
    }
    if (!textOverride.empty()) {
        style.textColor = textOverride;
    }
    if (!borderOverride.empty()) {
        style.borderColor = borderOverride;
    }
    if (!accentOverride.empty()) {
        style.accentColor = accentOverride;
    }

    style.borderThickness = std::clamp(widget.getFloatProperty("borderThickness", style.borderThickness), 0.0f, 20.0f);
    style.cornerRadius = std::clamp(widget.getFloatProperty("cornerRadius", style.cornerRadius), 0.0f, 50.0f);
    style.fontSize = std::clamp(widget.getFloatProperty("fontSize", style.fontSize), 8.0f, 72.0f);

    if (widget.type == visiform::model::WidgetType::FormWindow || widget.type == visiform::model::WidgetType::Frame) {
        const std::string backgroundOverride = widget.getStringProperty("backgroundColor", {});
        if (!backgroundOverride.empty()) {
            style.fillColor = backgroundOverride;
        }
    }

    return style;
}

std::string widgetLabel(const visiform::model::WidgetNode& widget)
{
    if (!widget.name.empty()) {
        return widget.name;
    }
    if (!widget.id.empty()) {
        return widget.id;
    }

    return widget.typeName();
}

enum class HandlerSignature {
    Void,
    Bool,
    Float,
    String
};

struct EventBinding {
    std::string eventKey;
    std::string handlerName;
    std::string widgetId;
    HandlerSignature signature = HandlerSignature::Void;
};

struct HandlerInfo {
    std::string handlerName;
    HandlerSignature signature = HandlerSignature::Void;
    std::vector<EventBinding> bindings{};
};

using PreservedUserCodeBlocks = std::unordered_map<std::string, std::string>;

std::string trimNewlines(std::string text)
{
    while (!text.empty() && (text.front() == '\r' || text.front() == '\n')) {
        text.erase(text.begin());
    }
    while (!text.empty() && (text.back() == '\r' || text.back() == '\n')) {
        text.pop_back();
    }
    return text;
}

PreservedUserCodeBlocks extractPreservedUserCodeBlocks(const std::string& existingMainWindowCpp)
{
    PreservedUserCodeBlocks blocks;
    std::size_t searchStart = 0;
    while (true) {
        const std::size_t beginMarker = existingMainWindowCpp.find("// USER CODE BEGIN ", searchStart);
        if (beginMarker == std::string::npos) {
            break;
        }

        const std::size_t handlerNameStart = beginMarker + std::string("// USER CODE BEGIN ").size();
        const std::size_t handlerNameEnd = existingMainWindowCpp.find('\n', handlerNameStart);
        if (handlerNameEnd == std::string::npos) {
            break;
        }

        const std::string handlerName = trimNewlines(existingMainWindowCpp.substr(handlerNameStart, handlerNameEnd - handlerNameStart));
        const std::string endMarkerText = "// USER CODE END " + handlerName;
        const std::size_t endMarker = existingMainWindowCpp.find(endMarkerText, handlerNameEnd);
        if (endMarker == std::string::npos) {
            searchStart = handlerNameEnd;
            continue;
        }

        std::string preservedBody = existingMainWindowCpp.substr(handlerNameEnd + 1, endMarker - (handlerNameEnd + 1));
        blocks.insert_or_assign(handlerName, trimNewlines(std::move(preservedBody)));
        searchStart = endMarker + endMarkerText.size();
    }

    return blocks;
}

std::vector<std::string> relevantEventKeys(visiform::model::WidgetType type)
{
    switch (type) {
    case visiform::model::WidgetType::Button:
        return { "onClick" };
    case visiform::model::WidgetType::CheckBox:
        return { "onToggle" };
    case visiform::model::WidgetType::RadioButton:
        return { "onSelected" };
    case visiform::model::WidgetType::Slider:
    case visiform::model::WidgetType::ScrollBar:
        return { "onChanged" };
    case visiform::model::WidgetType::TextBox:
        return { "onTextChanged" };
    case visiform::model::WidgetType::FormWindow:
        return { "onLoad", "onClose" };
    case visiform::model::WidgetType::Label:
    case visiform::model::WidgetType::Frame:
    case visiform::model::WidgetType::Image:
    case visiform::model::WidgetType::Spacer:
        return {};
    }

    return {};
}

HandlerSignature signatureForEventKey(const std::string& eventKey)
{
    if (eventKey == "onToggle") {
        return HandlerSignature::Bool;
    }
    if (eventKey == "onSelected") {
        return HandlerSignature::Bool;
    }
    if (eventKey == "onChanged") {
        return HandlerSignature::Float;
    }
    if (eventKey == "onTextChanged") {
        return HandlerSignature::String;
    }

    return HandlerSignature::Void;
}

std::string signatureDescription(HandlerSignature signature)
{
    switch (signature) {
    case HandlerSignature::Void:
        return "void(const WidgetEvent&)";
    case HandlerSignature::Bool:
        return "void(const WidgetEvent&, bool)";
    case HandlerSignature::Float:
        return "void(const WidgetEvent&, float)";
    case HandlerSignature::String:
        return "void(const WidgetEvent&, const std::string&)";
    }

    return "void(const WidgetEvent&)";
}

std::string handlerDeclaration(const HandlerInfo& handler)
{
    switch (handler.signature) {
    case HandlerSignature::Void:
        return "void " + handler.handlerName + "(const WidgetEvent& event);";
    case HandlerSignature::Bool:
        return "void " + handler.handlerName + "(const WidgetEvent& event, bool value);";
    case HandlerSignature::Float:
        return "void " + handler.handlerName + "(const WidgetEvent& event, float value);";
    case HandlerSignature::String:
        return "void " + handler.handlerName + "(const WidgetEvent& event, const std::string& value);";
    }

    return "void " + handler.handlerName + "(const WidgetEvent& event);";
}

std::string handlerDefinitionSignature(const std::string& className, const HandlerInfo& handler)
{
    switch (handler.signature) {
    case HandlerSignature::Void:
        return "void " + className + "::" + handler.handlerName + "(const WidgetEvent& event)";
    case HandlerSignature::Bool:
        return "void " + className + "::" + handler.handlerName + "(const WidgetEvent& event, bool value)";
    case HandlerSignature::Float:
        return "void " + className + "::" + handler.handlerName + "(const WidgetEvent& event, float value)";
    case HandlerSignature::String:
        return "void " + className + "::" + handler.handlerName + "(const WidgetEvent& event, const std::string& value)";
    }

    return "void " + className + "::" + handler.handlerName + "(const WidgetEvent& event)";
}

std::string handlerTodoLine(const EventBinding& binding)
{
    return "// TODO: Implement " + binding.eventKey + " handler for " + binding.widgetId + ".";
}

std::string handlerReferenceList(const HandlerInfo& handler)
{
    std::ostringstream stream;
    for (std::size_t index = 0; index < handler.bindings.size(); ++index) {
        if (index > 0) {
            stream << ", ";
        }
        stream << handler.bindings[index].widgetId << "." << handler.bindings[index].eventKey;
    }
    return stream.str();
}

void collectEventBindings(const visiform::model::WidgetNode& widget, std::vector<EventBinding>& bindings, std::string& errorMessage)
{
    for (const auto& eventKey : relevantEventKeys(widget.type)) {
        const std::string handlerName = widget.getStringProperty(eventKey, {});
        if (handlerName.empty()) {
            continue;
        }

        if (!utils::isValidCppIdentifier(handlerName)) {
            errorMessage = "Invalid event handler name: " + handlerName;
            return;
        }

        bindings.push_back(EventBinding{ eventKey, handlerName, widget.id, signatureForEventKey(eventKey) });
    }

    for (const auto& child : widget.children) {
        collectEventBindings(child, bindings, errorMessage);
        if (!errorMessage.empty()) {
            return;
        }
    }
}

bool collectHandlers(const visiform::model::ProjectDocument& document, std::vector<HandlerInfo>& handlers, std::string& errorMessage)
{
    std::vector<EventBinding> bindings;
    collectEventBindings(document.root, bindings, errorMessage);
    if (!errorMessage.empty()) {
        return false;
    }

    std::map<std::string, std::size_t> handlerIndexByName;
    for (const auto& binding : bindings) {
        const auto [iterator, inserted] = handlerIndexByName.emplace(binding.handlerName, handlers.size());
        if (inserted) {
            handlers.push_back(HandlerInfo{ binding.handlerName, binding.signature, { binding } });
            continue;
        }

        auto& handler = handlers[iterator->second];
        if (handler.signature != binding.signature) {
            errorMessage = "Event handler name conflict: " + binding.handlerName + " has multiple signatures";
            return false;
        }

        handler.bindings.push_back(binding);
    }

    return true;
}

void emitEventComments(std::ostringstream& stream, const std::string& indent, const visiform::model::WidgetNode& widget)
{
    for (const auto& eventKey : relevantEventKeys(widget.type)) {
        const std::string handlerName = widget.getStringProperty(eventKey, {});
        if (handlerName.empty()) {
            continue;
        }

        stream << indent << "// Event: " << eventKey << " -> " << handlerName << "\n";
        stream << indent << "// Sender: " << widgetLabel(widget) << " (" << widget.id << ", " << widget.typeName() << ")\n";
        stream << indent << "// TODO: Connect this handler when generated interactive widgets are implemented.\n";
    }
}

void emitWidgetDraw(std::ostringstream& stream,
    const visiform::model::ProjectDocument& document,
    const visiform::model::WidgetNode& widget,
    float parentX,
    float parentY,
    int indentLevel)
{
    const std::string indent(indentLevel * 4, ' ');
    const std::string xExpr = emitFloat(parentX + widget.bounds.x);
    const std::string yExpr = emitFloat(parentY + widget.bounds.y);
    const std::string widthExpr = emitFloat(widget.bounds.width);
    const std::string heightExpr = emitFloat(widget.bounds.height);
    const ResolvedWidgetStyle style = resolveWidgetStyle(document, widget);
    emitEventComments(stream, indent, widget);
    const std::string widgetHint = widget.getStringProperty("hint", {});
    if (!widgetHint.empty()) {
        stream << indent << "// Hint: " << escapeCppStringLiteral(widgetHint) << "\n";
    }

    switch (widget.type) {
    case visiform::model::WidgetType::FormWindow:
        stream << indent << "canvas.setColor(" << emitColorExpression(style.fillColor, "0xff1F242D") << ");\n";
        stream << indent << "canvas.fill(" << xExpr << ", " << yExpr << ", " << widthExpr << ", " << heightExpr << ");\n";
        stream << indent << "canvas.setColor(" << emitColorExpression(style.panelColor, "0xff2B313D") << ");\n";
        stream << indent << "canvas.fill(" << xExpr << ", " << yExpr << ", " << widthExpr << ", 28.0f);\n";
        stream << indent << "drawBorder(canvas, " << xExpr << ", " << yExpr << ", " << widthExpr << ", " << heightExpr << ", " << emitColorExpression(style.borderColor, "0xff6C7788") << ", " << emitFloat(style.borderThickness) << ");\n";
        stream << indent << "if (drawText) {\n";
        stream << indent << "    canvas.setColor(" << emitColorExpression(style.textColor, "0xffEEF2F8") << ");\n";
        stream << indent << "    canvas.text(" << emitStringLiteral(widget.getStringProperty("title", widgetLabel(widget)))
               << ", labelFont_, visage::Font::kTopLeft, " << xExpr << " + 10.0f, " << yExpr << " + 4.0f, " << widthExpr << " - 20.0f, 22.0f);\n";
        stream << indent << "}\n";
        break;
    case visiform::model::WidgetType::Frame:
        stream << indent << "canvas.setColor(" << emitColorExpression(style.fillColor, "0xff2B313D") << ");\n";
        stream << indent << "canvas.fill(" << xExpr << ", " << yExpr << ", " << widthExpr << ", " << heightExpr << ");\n";
        stream << indent << "drawBorder(canvas, " << xExpr << ", " << yExpr << ", " << widthExpr << ", " << heightExpr << ", " << emitColorExpression(style.borderColor, "0xff97A3B7") << ", " << emitFloat(style.borderThickness) << ");\n";
        stream << indent << "if (drawText) {\n";
        stream << indent << "    canvas.setColor(" << emitColorExpression(style.textColor, "0xffEEF2F8") << ");\n";
        stream << indent << "    canvas.text(" << emitStringLiteral(widget.getStringProperty("title", widgetLabel(widget)))
               << ", labelFont_, visage::Font::kTopLeft, " << xExpr << " + 8.0f, " << yExpr << " + 6.0f, " << widthExpr << " - 16.0f, 20.0f);\n";
        stream << indent << "}\n";
        break;
    case visiform::model::WidgetType::Label:
        stream << indent << "if (drawText) {\n";
        stream << indent << "    canvas.setColor(" << emitColorExpression(style.textColor, "0xffEEF2F8") << ");\n";
        stream << indent << "    canvas.text(" << emitStringLiteral(displayTextOrFallback(widget, "text", "Label"))
               << ", labelFont_, visage::Font::kTopLeft, " << xExpr << " + 4.0f, " << yExpr << " + 3.0f, " << widthExpr << " - 4.0f, " << heightExpr << " - 4.0f);\n";
        stream << indent << "}\n";
        break;
    case visiform::model::WidgetType::Button:
        stream << indent << "canvas.setColor(" << emitColorExpression(style.fillColor, "0xff2B313D") << ");\n";
        stream << indent << "canvas.fill(" << xExpr << ", " << yExpr << ", " << widthExpr << ", " << heightExpr << ");\n";
        stream << indent << "drawBorder(canvas, " << xExpr << ", " << yExpr << ", " << widthExpr << ", " << heightExpr << ", " << emitColorExpression(style.borderColor, "0xff97A3B7") << ", " << emitFloat(style.borderThickness) << ");\n";
        stream << indent << "if (drawText) {\n";
        stream << indent << "    canvas.setColor(" << emitColorExpression(style.textColor, "0xffEEF2F8") << ");\n";
        stream << indent << "    canvas.text(" << emitStringLiteral(widget.getStringProperty("text", widgetLabel(widget)))
               << ", labelFont_, visage::Font::kCenter, " << xExpr << ", " << yExpr << ", " << widthExpr << ", " << heightExpr << ");\n";
        stream << indent << "}\n";
        break;
    case visiform::model::WidgetType::TextBox:
        stream << indent << "canvas.setColor(" << emitColorExpression(style.fillColor, "0xffFFFFFF") << ");\n";
        stream << indent << "canvas.fill(" << xExpr << ", " << yExpr << ", " << widthExpr << ", " << heightExpr << ");\n";
        stream << indent << "drawBorder(canvas, " << xExpr << ", " << yExpr << ", " << widthExpr << ", " << heightExpr << ", " << emitColorExpression(style.borderColor, "0xff97A3B7") << ", " << emitFloat(style.borderThickness) << ");\n";
        stream << indent << "if (drawText) {\n";
        stream << indent << "    canvas.setColor(" << emitColorExpression(style.textColor, "0xffEEF2F8") << ");\n";
        stream << indent << "    canvas.text(" << emitStringLiteral(widget.getStringProperty("text", ""))
               << ", labelFont_, visage::Font::kTopLeft, " << xExpr << " + 8.0f, " << yExpr << " + 6.0f, " << widthExpr << " - 12.0f, " << heightExpr << " - 8.0f);\n";
        stream << indent << "}\n";
        break;
    case visiform::model::WidgetType::CheckBox:
        stream << indent << "canvas.setColor(" << emitColorExpression(style.fillColor, "0xffFFFFFF") << ");\n";
        stream << indent << "canvas.fill(" << xExpr << ", " << yExpr << " + (" << heightExpr << " - 18.0f) * 0.5f, 18.0f, 18.0f);\n";
        stream << indent << "drawBorder(canvas, " << xExpr << ", " << yExpr << " + (" << heightExpr << " - 18.0f) * 0.5f, 18.0f, 18.0f, " << emitColorExpression(style.borderColor, "0xff97A3B7") << ", " << emitFloat(style.borderThickness) << ");\n";
        if (widget.getBoolProperty("checked", false)) {
            stream << indent << "canvas.setColor(" << emitColorExpression(style.accentColor, "0xff2D7FF9") << ");\n";
            stream << indent << "canvas.fill(" << xExpr << " + 4.0f, " << yExpr << " + (" << heightExpr << " - 10.0f) * 0.5f, 10.0f, 10.0f);\n";
        }
        stream << indent << "if (drawText) {\n";
        stream << indent << "    canvas.setColor(" << emitColorExpression(style.textColor, "0xffEEF2F8") << ");\n";
        stream << indent << "    canvas.text(" << emitStringLiteral(displayTextOrFallback(widget, "text", "CheckBox"))
               << ", labelFont_, visage::Font::kTopLeft, " << xExpr << " + 26.0f, " << yExpr << " + 4.0f, " << widthExpr << " - 30.0f, " << heightExpr << " - 6.0f);\n";
        stream << indent << "}\n";
        break;
    case visiform::model::WidgetType::RadioButton:
        stream << indent << "canvas.setColor(" << emitColorExpression(style.fillColor, "0xffFFFFFF") << ");\n";
        stream << indent << "canvas.fill(" << xExpr << ", " << yExpr << " + (" << heightExpr << " - 18.0f) * 0.5f, 18.0f, 18.0f);\n";
        stream << indent << "drawBorder(canvas, " << xExpr << ", " << yExpr << " + (" << heightExpr << " - 18.0f) * 0.5f, 18.0f, 18.0f, " << emitColorExpression(style.borderColor, "0xff97A3B7") << ", " << emitFloat(style.borderThickness) << ");\n";
        if (widget.getBoolProperty("selected", false)) {
            stream << indent << "canvas.setColor(" << emitColorExpression(style.accentColor, "0xff2D7FF9") << ");\n";
            stream << indent << "canvas.fill(" << xExpr << " + 5.0f, " << yExpr << " + (" << heightExpr << " - 8.0f) * 0.5f, 8.0f, 8.0f);\n";
        }
        stream << indent << "if (drawText) {\n";
        stream << indent << "    canvas.setColor(" << emitColorExpression(style.textColor, "0xffEEF2F8") << ");\n";
        stream << indent << "    canvas.text(" << emitStringLiteral(displayTextOrFallback(widget, "text", "Radio Button"))
               << ", labelFont_, visage::Font::kTopLeft, " << xExpr << " + 26.0f, " << yExpr << " + 4.0f, " << widthExpr << " - 30.0f, " << heightExpr << " - 6.0f);\n";
        stream << indent << "}\n";
        break;
    case visiform::model::WidgetType::Slider: {
        const float minValue = widget.getFloatProperty("min", 0.0f);
        const float maxValue = widget.getFloatProperty("max", 100.0f);
        const float currentValue = widget.getFloatProperty("value", 50.0f);
        const float denominator = maxValue > minValue ? (maxValue - minValue) : 1.0f;
        const float normalized = std::clamp((currentValue - minValue) / denominator, 0.0f, 1.0f);
        stream << indent << "canvas.setColor(" << emitColorExpression(style.borderColor, "0xff97A3B7") << ");\n";
        stream << indent << "canvas.fill(" << xExpr << " + 8.0f, " << yExpr << " + " << heightExpr << " * 0.5f - 2.0f, " << widthExpr << " - 16.0f, 4.0f);\n";
        stream << indent << "canvas.setColor(" << emitColorExpression(style.accentColor, "0xff2D7FF9") << ");\n";
        stream << indent << "canvas.fill(" << xExpr << " + 8.0f + (" << widthExpr << " - 28.0f) * " << emitFloat(normalized)
               << ", " << yExpr << " + " << heightExpr << " * 0.5f - 8.0f, 12.0f, 16.0f);\n";
        break;
    }
    case visiform::model::WidgetType::ScrollBar: {
        const bool vertical = widget.getStringProperty("orientation", "Horizontal") == "Vertical";
        const float minValue = widget.getFloatProperty("min", 0.0f);
        const float maxValue = std::max(minValue + 1.0f, widget.getFloatProperty("max", 100.0f));
        const float currentValue = std::clamp(widget.getFloatProperty("value", 0.0f), minValue, maxValue);
        const float pageSize = std::max(1.0f, widget.getFloatProperty("pageSize", 10.0f));
        const float normalized = std::clamp((currentValue - minValue) / (maxValue - minValue), 0.0f, 1.0f);
        const float thumbFactor = std::clamp(pageSize / (maxValue - minValue + pageSize), 0.18f, 0.55f);
        stream << indent << "canvas.setColor(" << emitColorExpression(style.fillColor, "0xffD7DEE8") << ");\n";
        stream << indent << "canvas.fill(" << xExpr << ", " << yExpr << ", " << widthExpr << ", " << heightExpr << ");\n";
        stream << indent << "drawBorder(canvas, " << xExpr << ", " << yExpr << ", " << widthExpr << ", " << heightExpr << ", " << emitColorExpression(style.borderColor, "0xff97A3B7") << ", " << emitFloat(style.borderThickness) << ");\n";
        if (vertical) {
            stream << indent << "const float arrowSize = std::min(" << widthExpr << ", 20.0f);\n";
            stream << indent << "const float trackTop = " << yExpr << " + arrowSize;\n";
            stream << indent << "const float trackHeight = std::max(0.0f, " << heightExpr << " - arrowSize * 2.0f);\n";
            stream << indent << "const float thumbHeight = std::clamp(trackHeight * " << emitFloat(thumbFactor) << ", 18.0f, std::max(18.0f, trackHeight));\n";
            stream << indent << "const float thumbY = trackTop + std::max(0.0f, trackHeight - thumbHeight) * " << emitFloat(normalized) << ";\n";
            stream << indent << "canvas.setColor(" << emitColorExpression(style.fillColor, "0xffEEF2F8") << ");\n";
            stream << indent << "canvas.fill(" << xExpr << ", " << yExpr << ", " << widthExpr << ", arrowSize);\n";
            stream << indent << "canvas.fill(" << xExpr << ", " << yExpr << " + " << heightExpr << " - arrowSize, " << widthExpr << ", arrowSize);\n";
            stream << indent << "drawBorder(canvas, " << xExpr << ", " << yExpr << ", " << widthExpr << ", arrowSize, " << emitColorExpression(style.borderColor, "0xff97A3B7") << ", " << emitFloat(style.borderThickness) << ");\n";
            stream << indent << "drawBorder(canvas, " << xExpr << ", " << yExpr << " + " << heightExpr << " - arrowSize, " << widthExpr << ", arrowSize, " << emitColorExpression(style.borderColor, "0xff97A3B7") << ", " << emitFloat(style.borderThickness) << ");\n";
            stream << indent << "canvas.setColor(" << emitColorExpression(style.panelColor, "0xff1F242D") << ");\n";
            stream << indent << "canvas.fill(" << xExpr << " + 2.0f, trackTop, " << widthExpr << " - 4.0f, trackHeight);\n";
            stream << indent << "canvas.setColor(" << emitColorExpression(style.accentColor, "0xff2D7FF9") << ");\n";
            stream << indent << "canvas.fill(" << xExpr << " + 4.0f, thumbY, " << widthExpr << " - 8.0f, thumbHeight);\n";
            stream << indent << "drawBorder(canvas, " << xExpr << " + 4.0f, thumbY, " << widthExpr << " - 8.0f, thumbHeight, " << emitColorExpression(style.borderColor, "0xff97A3B7") << ", " << emitFloat(style.borderThickness) << ");\n";
        }
        else {
            stream << indent << "const float arrowSize = std::min(" << heightExpr << ", 20.0f);\n";
            stream << indent << "const float trackLeft = " << xExpr << " + arrowSize;\n";
            stream << indent << "const float trackWidth = std::max(0.0f, " << widthExpr << " - arrowSize * 2.0f);\n";
            stream << indent << "const float thumbWidth = std::clamp(trackWidth * " << emitFloat(thumbFactor) << ", 18.0f, std::max(18.0f, trackWidth));\n";
            stream << indent << "const float thumbX = trackLeft + std::max(0.0f, trackWidth - thumbWidth) * " << emitFloat(normalized) << ";\n";
            stream << indent << "canvas.setColor(" << emitColorExpression(style.fillColor, "0xffEEF2F8") << ");\n";
            stream << indent << "canvas.fill(" << xExpr << ", " << yExpr << ", arrowSize, " << heightExpr << ");\n";
            stream << indent << "canvas.fill(" << xExpr << " + " << widthExpr << " - arrowSize, " << yExpr << ", arrowSize, " << heightExpr << ");\n";
            stream << indent << "drawBorder(canvas, " << xExpr << ", " << yExpr << ", arrowSize, " << heightExpr << ", " << emitColorExpression(style.borderColor, "0xff97A3B7") << ", " << emitFloat(style.borderThickness) << ");\n";
            stream << indent << "drawBorder(canvas, " << xExpr << " + " << widthExpr << " - arrowSize, " << yExpr << ", arrowSize, " << heightExpr << ", " << emitColorExpression(style.borderColor, "0xff97A3B7") << ", " << emitFloat(style.borderThickness) << ");\n";
            stream << indent << "canvas.setColor(" << emitColorExpression(style.panelColor, "0xff1F242D") << ");\n";
            stream << indent << "canvas.fill(trackLeft, " << yExpr << " + 2.0f, trackWidth, " << heightExpr << " - 4.0f);\n";
            stream << indent << "canvas.setColor(" << emitColorExpression(style.accentColor, "0xff2D7FF9") << ");\n";
            stream << indent << "canvas.fill(thumbX, " << yExpr << " + 4.0f, thumbWidth, " << heightExpr << " - 8.0f);\n";
            stream << indent << "drawBorder(canvas, thumbX, " << yExpr << " + 4.0f, thumbWidth, " << heightExpr << " - 8.0f, " << emitColorExpression(style.borderColor, "0xff97A3B7") << ", " << emitFloat(style.borderThickness) << ");\n";
        }
        break;
    }
    case visiform::model::WidgetType::StatusBar: {
        const int fields = std::clamp(widget.getIntProperty("fields", 1), 1, 4);
        stream << indent << "canvas.setColor(" << emitColorExpression(style.fillColor, "0xff2B313D") << ");\n";
        stream << indent << "canvas.fill(" << xExpr << ", " << yExpr << ", " << widthExpr << ", " << heightExpr << ");\n";
        stream << indent << "drawBorder(canvas, " << xExpr << ", " << yExpr << ", " << widthExpr << ", " << heightExpr << ", " << emitColorExpression(style.borderColor, "0xff6C7788") << ", " << emitFloat(style.borderThickness) << ");\n";
        stream << indent << "if (drawText) {\n";
        stream << indent << "    const float fieldWidth = " << widthExpr << " / " << fields << ".0f;\n";
        for (int index = 0; index < fields; ++index) {
            const std::string textKey = "text" + std::to_string(index);
            stream << indent << "    canvas.setColor(" << emitColorExpression(style.textColor, "0xffEEF2F8") << ");\n";
            stream << indent << "    canvas.text(" << emitStringLiteral(widget.getStringProperty(textKey, index == 0 ? "Ready" : ""))
                   << ", labelFont_, visage::Font::kTopLeft, " << xExpr << " + fieldWidth * " << index << ".0f + 6.0f, " << yExpr << " + 6.0f, fieldWidth - 12.0f, " << heightExpr << " - 12.0f);\n";
            if (index + 1 < fields) {
                stream << indent << "    canvas.setColor(" << emitColorExpression(style.borderColor, "0xff6C7788") << ");\n";
                stream << indent << "    canvas.fill(" << xExpr << " + fieldWidth * " << (index + 1) << ".0f - 1.0f, " << yExpr << " + 4.0f, 1.0f, " << heightExpr << " - 8.0f);\n";
            }
        }
        stream << indent << "}\n";
        break;
    }
    case visiform::model::WidgetType::ProgressBar: {
        const float minValue = widget.getFloatProperty("min", 0.0f);
        const float maxValue = std::max(minValue + 1.0f, widget.getFloatProperty("max", 100.0f));
        const float currentValue = std::clamp(widget.getFloatProperty("value", 25.0f), minValue, maxValue);
        const float normalized = std::clamp((currentValue - minValue) / (maxValue - minValue), 0.0f, 1.0f);
        const std::string displayText = progressBarDisplayText(widget);
        stream << indent << "canvas.setColor(" << emitColorExpression(style.fillColor, "0xffEEF2F7") << ");\n";
        stream << indent << "canvas.fill(" << xExpr << ", " << yExpr << ", " << widthExpr << ", " << heightExpr << ");\n";
        stream << indent << "drawBorder(canvas, " << xExpr << ", " << yExpr << ", " << widthExpr << ", " << heightExpr << ", " << emitColorExpression(style.borderColor, "0xff97A3B7") << ", " << emitFloat(style.borderThickness) << ");\n";
        stream << indent << "canvas.setColor(" << emitColorExpression(style.accentColor, "0xff2D7FF9") << ");\n";
        stream << indent << "canvas.fill(" << xExpr << ", " << yExpr << ", " << widthExpr << " * " << emitFloat(normalized) << ", " << heightExpr << ");\n";
        if (!displayText.empty()) {
            stream << indent << "canvas.setColor(" << (normalized >= 0.5f ? "0xffF8FBFF" : emitColorExpression(style.textColor, "0xff182333")) << ");\n";
            stream << indent << "canvas.text(" << emitStringLiteral(displayText)
                   << ", labelFont_, visage::Font::kCenter, " << xExpr << ", " << yExpr << ", " << widthExpr << ", " << heightExpr << ");\n";
        }
        break;
    }
    case visiform::model::WidgetType::Image:
        stream << indent << "canvas.setColor(" << emitColorExpression(style.fillColor, "0xffD3DAE6") << ");\n";
        stream << indent << "canvas.fill(" << xExpr << ", " << yExpr << ", " << widthExpr << ", " << heightExpr << ");\n";
        stream << indent << "drawBorder(canvas, " << xExpr << ", " << yExpr << ", " << widthExpr << ", " << heightExpr << ", " << emitColorExpression(style.borderColor, "0xff97A3B7") << ", " << emitFloat(style.borderThickness) << ");\n";
        stream << indent << "if (drawText) {\n";
        stream << indent << "    canvas.setColor(" << emitColorExpression(style.textColor, "0xffEEF2F8") << ");\n";
        stream << indent << "    canvas.text(" << emitStringLiteral(widget.getStringProperty("source", widgetLabel(widget)))
               << ", labelFont_, visage::Font::kCenter, " << xExpr << ", " << yExpr << ", " << widthExpr << ", " << heightExpr << ");\n";
        stream << indent << "}\n";
        break;
    case visiform::model::WidgetType::Spacer:
        stream << indent << "canvas.setColor(" << emitColorExpression(style.fillColor, "0xff2B313D") << ");\n";
        stream << indent << "canvas.fill(" << xExpr << ", " << yExpr << ", " << widthExpr << ", " << heightExpr << ");\n";
        stream << indent << "drawBorder(canvas, " << xExpr << ", " << yExpr << ", " << widthExpr << ", " << heightExpr << ", " << emitColorExpression(style.borderColor, "0xff97A3B7") << ", " << emitFloat(style.borderThickness) << ");\n";
        stream << indent << "if (drawText) {\n";
        stream << indent << "    canvas.setColor(" << emitColorExpression(style.textColor, "0xffEEF2F8") << ");\n";
        stream << indent << "    canvas.text(\"Spacer\", labelFont_, visage::Font::kCenter, " << xExpr << ", " << yExpr << ", " << widthExpr << ", " << heightExpr << ");\n";
        stream << indent << "}\n";
        break;
    }

    for (const auto& child : widget.children) {
        emitWidgetDraw(stream, document, child, parentX + widget.bounds.x, parentY + widget.bounds.y, indentLevel);
    }
}

std::string emitGeneratedBaseHeader(const visiform::model::ProjectDocument& document)
{
    const std::string className = generatedBaseClassName(document);
    std::vector<HandlerInfo> handlers;
    std::string ignoredError;
    collectHandlers(document, handlers, ignoredError);
    std::ostringstream stream;
    stream << kGeneratedFileHeader;
    stream << "#pragma once\n\n";
    stream << "#include <string>\n";
    stream << "#include <visage/app.h>\n";
    stream << "#include <visage/graphics.h>\n\n";
    stream << "struct WidgetEvent {\n";
    stream << "    const char* senderId = \"\";\n";
    stream << "    const char* senderName = \"\";\n";
    stream << "    const char* senderType = \"\";\n";
    stream << "};\n\n";
    stream << "class " << className << " : public visage::ApplicationWindow {\n";
    stream << "public:\n";
    stream << "    " << className << "();\n";
    stream << "    ~" << className << "() override = default;\n\n";
    stream << "    void showWindow();\n";
    stream << "    void draw(visage::Canvas& canvas) override;\n\n";
    stream << "protected:\n";
    for (const auto& handler : handlers) {
        stream << "    // Referenced by: " << handlerReferenceList(handler) << "\n";
        std::string declaration = handlerDeclaration(handler);
        if (!declaration.empty() && declaration.back() == ';') {
            declaration.pop_back();
        }
        stream << "    virtual " << declaration << ";\n";
    }
    if (!handlers.empty()) {
        stream << "\n";
    }
    stream << "private:\n";
    stream << "    bool canDrawText() const;\n\n";
    stream << "    visage::Font labelFont_{};\n";
    stream << "};\n";
    return stream.str();
}

std::string emitMainCpp(const visiform::model::ProjectDocument& document)
{
    const std::string className = userSubclassName(document);
    std::ostringstream stream;
    stream << kGeneratedFileHeader;
    stream << "#include \"" << className << ".h\"\n\n";
    stream << "#include <exception>\n";
    stream << "#include <iostream>\n\n";
    stream << "int main()\n";
    stream << "{\n";
    stream << "    try {\n";
    stream << "        " << className << " window;\n";
    stream << "        window.showWindow();\n";
    stream << "        if (!window.isShowing()) {\n";
    stream << "            throw std::runtime_error(\"The generated Visage window did not open.\");\n";
    stream << "        }\n";
    stream << "\n";
    stream << "        window.runEventLoop();\n";
    stream << "        return 0;\n";
    stream << "    }\n";
    stream << "    catch (const std::exception& exception) {\n";
    stream << "        std::cerr << \"Generated Visage project failed to start: \" << exception.what() << '\\n';\n";
    stream << "    }\n";
    stream << "    catch (...) {\n";
    stream << "        std::cerr << \"Generated Visage project failed to start with an unknown error.\\n\";\n";
    stream << "    }\n\n";
    stream << "    return 1;\n";
    stream << "}\n";
    return stream.str();
}

std::string emitGeneratedBaseCpp(const visiform::model::ProjectDocument& document)
{
    const std::string className = generatedBaseClassName(document);
    const std::string windowTitle = document.root.getStringProperty("title", userSubclassName(document));
    const float windowWidth = std::max(1000.0f, document.root.bounds.width + 120.0f);
    const float windowHeight = std::max(800.0f, document.root.bounds.height + 120.0f);
    std::vector<HandlerInfo> handlers;
    std::string ignoredError;
    collectHandlers(document, handlers, ignoredError);

    std::ostringstream stream;
    stream << kGeneratedFileHeader;
    stream << "#include \"" << className << ".h\"\n\n";
    stream << "#include <array>\n";
    stream << "#include <fstream>\n";
    stream << "#include <string>\n\n";
    stream << "namespace {\n\n";
    stream << "void drawBorder(visage::Canvas& canvas, float x, float y, float width, float height, int color, float thickness = 1.0f)\n";
    stream << "{\n";
    stream << "    canvas.setColor(color);\n";
    stream << "    canvas.fill(x, y, width, thickness);\n";
    stream << "    canvas.fill(x, y + height - thickness, width, thickness);\n";
    stream << "    canvas.fill(x, y, thickness, height);\n";
    stream << "    canvas.fill(x + width - thickness, y, thickness, height);\n";
    stream << "}\n\n";
    stream << "} // namespace\n\n";
    stream << className << "::" << className << "()\n";
    stream << "{\n";
    stream << "    setTitle(" << emitStringLiteral(windowTitle) << ");\n";
    stream << "\n";
    stream << "    static constexpr std::array<const char*, 3> kFontCandidates = {\n";
    stream << "        \"C:/Windows/Fonts/segoeui.ttf\",\n";
    stream << "        \"C:/Windows/Fonts/tahoma.ttf\",\n";
    stream << "        \"C:/Windows/Fonts/arial.ttf\"\n";
    stream << "    };\n\n";
    stream << "    for (const char* fontPath : kFontCandidates) {\n";
    stream << "        std::ifstream fontFile(fontPath, std::ios::binary);\n";
    stream << "        if (!fontFile.good()) {\n";
    stream << "            continue;\n";
    stream << "        }\n\n";
    stream << "        labelFont_ = visage::Font(18.0f, std::string{ fontPath });\n";
    stream << "        if (canDrawText()) {\n";
    stream << "            break;\n";
    stream << "        }\n";
    stream << "    }\n";
    stream << "}\n\n";
    stream << "void " << className << "::showWindow()\n";
    stream << "{\n";
    stream << "    show(visage::Dimension::logicalPixels(" << emitFloat(windowWidth) << "), visage::Dimension::logicalPixels(" << emitFloat(windowHeight) << "));\n";
    stream << "}\n\n";
    stream << "void " << className << "::draw(visage::Canvas& canvas)\n";
    stream << "{\n";
    stream << "    canvas.setColor(0xff1B1D23);\n";
    stream << "    canvas.fill(0.0f, 0.0f, width(), height());\n\n";
    stream << "    const bool drawText = canDrawText();\n";
    stream << "    const float formOffsetX = 40.0f;\n";
    stream << "    const float formOffsetY = 60.0f;\n\n";
    emitWidgetDraw(stream, document, document.root, 40.0f, 60.0f, 1);
    stream << "}\n\n";
    stream << "bool " << className << "::canDrawText() const\n";
    stream << "{\n";
    stream << "    return labelFont_.packedFont() != nullptr;\n";
    stream << "}\n";

    for (const auto& handler : handlers) {
        stream << "\n" << handlerDefinitionSignature(className, handler) << "\n";
        stream << "{\n";
        stream << "    // References: " << handlerReferenceList(handler) << "\n";
        stream << "    (void)event;\n";
        if (handler.signature == HandlerSignature::Bool) {
            stream << "    (void)value;\n";
        }
        else if (handler.signature == HandlerSignature::Float) {
            stream << "    (void)value;\n";
        }
        else if (handler.signature == HandlerSignature::String) {
            stream << "    (void)value;\n";
        }
        stream << "    // Default generated event hook.\n";
        stream << "}\n";
    }
    return stream.str();
}

std::string emitUserSubclassHeader(const visiform::model::ProjectDocument& document)
{
    const std::string baseClass = generatedBaseClassName(document);
    const std::string userClass = userSubclassName(document);
    std::vector<HandlerInfo> handlers;
    std::string ignoredError;
    collectHandlers(document, handlers, ignoredError);

    std::ostringstream stream;
    stream << kGeneratedFileHeader;
    stream << "#pragma once\n\n";
    stream << "#include \"" << baseClass << ".h\"\n\n";
    stream << "class " << userClass << " : public " << baseClass << " {\n";
    stream << "public:\n";
    stream << "    " << userClass << "();\n";
    stream << "    ~" << userClass << "() override = default;\n";
    if (!handlers.empty()) {
        stream << "\nprotected:\n";
        for (const auto& handler : handlers) {
            std::string declaration = handlerDeclaration(handler);
            if (!declaration.empty() && declaration.back() == ';') {
                declaration.pop_back();
            }
            stream << "    " << declaration << " override;\n";
        }
    }
    stream << "};\n";
    return stream.str();
}

std::string emitUserSubclassCpp(const visiform::model::ProjectDocument& document, const std::string& existingUserCpp)
{
    const std::string userClass = userSubclassName(document);
    std::vector<HandlerInfo> handlers;
    std::string ignoredError;
    collectHandlers(document, handlers, ignoredError);
    const PreservedUserCodeBlocks preservedUserCodeBlocks = extractPreservedUserCodeBlocks(existingUserCpp);

    std::ostringstream stream;
    stream << kGeneratedFileHeader;
    stream << "#include \"" << userClass << ".h\"\n\n";
    stream << userClass << "::" << userClass << "() = default;\n";

    for (const auto& handler : handlers) {
        stream << "\n" << handlerDefinitionSignature(userClass, handler) << "\n";
        stream << "{\n";
        stream << "    // References: " << handlerReferenceList(handler) << "\n";
        stream << "    // USER CODE BEGIN " << handler.handlerName << "\n";
        if (const auto iterator = preservedUserCodeBlocks.find(handler.handlerName); iterator != preservedUserCodeBlocks.end() && !iterator->second.empty()) {
            std::istringstream preservedStream(iterator->second);
            std::string preservedLine;
            while (std::getline(preservedStream, preservedLine)) {
                stream << "    " << preservedLine << "\n";
            }
        }
        else {
            stream << "    (void)event;\n";
            if (handler.signature == HandlerSignature::Bool) {
                stream << "    (void)value;\n";
            }
            else if (handler.signature == HandlerSignature::Float) {
                stream << "    (void)value;\n";
            }
            else if (handler.signature == HandlerSignature::String) {
                stream << "    (void)value;\n";
            }
            stream << "    " << handlerTodoLine(handler.bindings.front()) << "\n";
        }
        stream << "    // USER CODE END " << handler.handlerName << "\n";
        stream << "}\n";
    }
    return stream.str();
}

} // namespace

bool VisageCppEmitter::emitProjectSources(
    const model::ProjectDocument& document,
    const std::string& existingMainWindowCpp,
    EmittedSources& output,
    std::string& errorMessage) const
{
    errorMessage.clear();
    std::vector<HandlerInfo> handlers;
    if (!collectHandlers(document, handlers, errorMessage)) {
        return false;
    }

    output = {
        emitMainCpp(document),
        "MainWindow.h",
        emitGeneratedBaseHeader(document),
        "MainWindow.cpp",
        emitGeneratedBaseCpp(document),
        userSubclassName(document) + ".h",
        emitUserSubclassHeader(document),
        userSubclassName(document) + ".cpp",
        emitUserSubclassCpp(document, existingMainWindowCpp)
    };
    return true;
}

} // namespace visiform::generator
